name: colourpycker
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.*
  - ipykernel
  - ipywidgets
  - pandas
  - numpy
  - altair
  - requests
  - pytest
  - pip
  - pip:
      - extcolors
      - pillow
      - pytest
      - poetry
